### ISSUE TITLE
Continued improvements

### ISSUE THREAD

**Issue by ericmichael** [adamjstevenson/stripe-connect-managed-rails#1]
Hi Adam,

This repo is a great example for learning to use Stripe Connect.
I teach at the University of Texas-Rio Grande Valley.
I have a small team of students that are using this repo to begin our understanding of Stripe Connect for their capstone project.

I was wondering if you would be be open to reviewing some PRs for some updates to this repo?

All the best,

Eric

**Comment by adamjstevenson** [comment]
Hey @ericmichael, sorry for the delay and definitely! I created this back in 2016 and have made some updates along the way, but this could certainly benefit from some improvements.
